### PR TITLE
Microsoft mandatory file

### PR DESCRIPTION
**Pull request by epworth**
R

### CODE REVIEW

**Comment by sophacola** [comment]
🧿🧿🧿👁️👁️👁️‍🗨️👁️‍🗨️👁️‍🗨️👁️‍🗨️👁️‍🗨️👁️👁️👀🧿🧿👀👀👁️👁️👁️👁️‍🗨️👁️‍🗨️👁️👁️👁️🕵️🕵️🕵️🕵️🕵️🕵️🕵️🕵️🕵️🕵️🕵️🕵️🕵️‍♀️🕵️‍♀️👁️‍🗨️👁️👁️😍😍😍😍😍😍🧿🧿🧿👁️👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀👀

**Review by sophacola — APPROVED** [review]

**Comment by sophacola** [comment]
🌈🌈🌈🌈🌈🌈🌈👀🙏🏾👀

**Review by Tamaloco — APPROVED** [review]
[](url)

**Review by FelixKLG — APPROVED** [review]

**Review by tobycm — APPROVED** [review]

**Comment by roblourens** [comment]
We already have this file checked in

**Pull request closed without merging**
